[package]
name = "gb-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"

[build-dependencies]
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
prettyplease = "0.2.37"
syn = "2.0.106"
proc-macro2 = "1.0.101"
